/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Checkbox.Group': typeof import('yep-ui')['CheckboxGroup']
    'Checkbox.Root': typeof import('yep-ui')['CheckboxRoot']
    'Dialog.Close': typeof import('yep-ui')['DialogClose']
    'Dialog.Panel': typeof import('yep-ui')['DialogPanel']
    'Dialog.Root': typeof import('yep-ui')['DialogRoot']
    'Dialog.Trigger': typeof import('yep-ui')['DialogTrigger']
  }
}
