// /* eslint-disable */
// /* prettier-ignore */
// // @ts-nocheck
// // Generated by unplugin-vue-components
// // Read more: https://github.com/vuejs/core/pull/3399
// import '@vue/runtime-core'

// export {}

// declare module '@vue/runtime-core' {
//   export interface GlobalComponents {
//     'Checkbox.Group': typeof import('yep-ui')['CheckboxGroup']
//     'Checkbox.Root': typeof import('yep-ui')['CheckboxRoot']
//     'Collapse.Panel': typeof import('yep-ui')['CollapsePanel']
//     'Collapse.Root': typeof import('yep-ui')['CollapseRoot']
//     'Collapse.Trigger': typeof import('yep-ui')['CollapseTrigger']
//     'Dialog.Close': typeof import('yep-ui')['DialogClose']
//     'Dialog.Panel': typeof import('yep-ui')['DialogPanel']
//     'Dialog.Root': typeof import('yep-ui')['DialogRoot']
//     'Dialog.Trigger': typeof import('yep-ui')['DialogTrigger']
//     'Input.Clear': typeof import('yep-ui')['InputClear']
//     'Input.Group': typeof import('yep-ui')['InputGroup']
//     'Input.Root': typeof import('yep-ui')['InputRoot']
//     'Popper.Anchor': typeof import('yep-ui')['PopperAnchor']
//     'Popper.Panel': typeof import('yep-ui')['PopperPanel']
//     'Popper.PanelArrow': typeof import('yep-ui')['PopperPanelArrow']
//     'Popper.Root': typeof import('yep-ui')['PopperRoot']
//     'Popper.Trigger': typeof import('yep-ui')['PopperTrigger']
//     'RadioGroup.Label': typeof import('yep-ui')['RadioGroupLabel']
//     'RadioGroup.Option': typeof import('yep-ui')['RadioGroupOption']
//     'RadioGroup.Root': typeof import('yep-ui')['RadioGroupRoot']
//     'Select.Option': typeof import('yep-ui')['SelectOption']
//     'Select.Options': typeof import('yep-ui')['SelectOptions']
//     'Select.Root': typeof import('yep-ui')['SelectRoot']
//     'Select.Tigger': typeof import('yep-ui')['SelectTigger']
//     'Select.Trigger': typeof import('yep-ui')['SelectTrigger']
//     'Switch.Group': typeof import('yep-ui')['SwitchGroup']
//     'Switch.Label': typeof import('yep-ui')['SwitchLabel']
//     'Switch.Root': typeof import('yep-ui')['SwitchRoot']
//   }
// }
