/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
  const Checkbox: typeof import('yep-ui')['Checkbox']
  const Collapse: typeof import('yep-ui')['Collapse']
  const Dialog: typeof import('yep-ui')['Dialog']
  const Input: typeof import('yep-ui')['Input']
  const RadioGroup: typeof import('yep-ui')['RadioGroup']
  const Select: typeof import('yep-ui')['Select']
  const Switch: typeof import('yep-ui')['Switch']
}
// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface ComponentCustomProperties {
    readonly Checkbox: UnwrapRef<typeof import('yep-ui')['Checkbox']>
    readonly Collapse: UnwrapRef<typeof import('yep-ui')['Collapse']>
    readonly Dialog: UnwrapRef<typeof import('yep-ui')['Dialog']>
    readonly Input: UnwrapRef<typeof import('yep-ui')['Input']>
    readonly RadioGroup: UnwrapRef<typeof import('yep-ui')['RadioGroup']>
    readonly Select: UnwrapRef<typeof import('yep-ui')['Select']>
    readonly Switch: UnwrapRef<typeof import('yep-ui')['Switch']>
  }
}
