/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Checkbox.Group': typeof import('yep-ui')['CheckboxGroup']
    'Checkbox.Indicator': typeof import('yep-ui')['CheckboxIndicator']
    'Checkbox.Root': typeof import('yep-ui')['CheckboxRoot']
    'Input.Clear': typeof import('yep-ui')['InputClear']
    'Input.Group': typeof import('yep-ui')['InputGroup']
    'Input.Root': typeof import('yep-ui')['InputRoot']
    'Popper.Anchor': typeof import('yep-ui')['PopperAnchor']
    'Popper.Panel': typeof import('yep-ui')['PopperPanel']
    'Popper.PanelArrow': typeof import('yep-ui')['PopperPanelArrow']
    'Popper.Root': typeof import('yep-ui')['PopperRoot']
    'Popper.Trigger': typeof import('yep-ui')['PopperTrigger']
    'RadioGroup.Label': typeof import('yep-ui')['RadioGroupLabel']
    'RadioGroup.Option': typeof import('yep-ui')['RadioGroupOption']
    'RadioGroup.Root': typeof import('yep-ui')['RadioGroupRoot']
    'Switch.Group': typeof import('yep-ui')['SwitchGroup']
    'Switch.Label': typeof import('yep-ui')['SwitchLabel']
    'Switch.Root': typeof import('yep-ui')['SwitchRoot']
  }
}
