/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Dialog.Close': typeof import('yep-ui')['Dialog']['Close']
    'Dialog.Panel': typeof import('yep-ui')['Dialog']['Panel']
    'Dialog.Root': typeof import('yep-ui')['Dialog']['Root']
    'Dialog.Trigger': typeof import('yep-ui')['Dialog']['Trigger']
  }
}
